version: '3.8'
services:
  vscode:
    build: .
    volumes:
      - ../:/workspace
      # Docker
      - ~/.docker:/root/.docker
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      # On Linux and OSX, a symlink /mnt/ssh <-> ~/.ssh is
      # created in the container. On Windows, files are copied
      # from /mnt/ssh to ~/.ssh to fix permissions.
      - ~/.ssh:/mnt/ssh
      # Shell history persistence
      - ~/.zsh_history:/root/.zsh_history
      # Git config
      - ~/.gitconfig:/root/.gitconfig
      # Kubernetes
      # - ~/.kube:/root/.kube
    environment:
      - TZ=
    # Needed for debugging
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined
    entrypoint: zsh -c "while sleep 1000; do :; done"
  database:
    image: 'postgres:15'
    hostname: postgres
    init: true
    container_name: londonapi-db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=londonapi-db
      - POSTGRES_PORT=5432
    volumes:
      - './postgresql.conf:/etc/postgresql.conf'
    ports:
      - '${POSTGRES_PORT}:5432'
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - database
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped